[features]
seeds = false
skip-lint = false

[programs.devnet]
queue_marketplace = "DHNLLb8p9kSFg8AzVzXAVmkHVkcb8yDM3xMz9iXALcv1"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"